### PR TITLE
Add dependencies to rockspec file

### PR DESCRIPTION
**Pull request by barrelmaker97**
PR for #37 
* Updated dependencies to match the ones listed in the description
~* Switched from single quotes to double quotes~

### CODE REVIEW

**Comment by cdbattags** [comment]
Why the change to double quotes?

**Comment by barrelmaker97** [comment]
Just something my linter did :laughing: Happy to revert if you want

**Comment by cdbattags** [comment]
This package doesn't actually depend upon lua-resty-hmac if you look. I use the submodule explicitly so that I can release on OPM as well.

**Comment by barrelmaker97** [comment]
Duly noted! Updated.

**Comment by barrelmaker97** [comment]
Any other changes needed?

**Pull request closed without merging**
